export const Filters = {
  glass: [
    "Highball glass",
    "Old-fashioned glass",
    "Cocktail glass",
    "Copper Mug",
    "Whiskey Glass",
    "Collins glass",
    "Pousse cafe glass",
    "Champagne flute",
    "Whiskey sour glass",
    "Brandy snifter",
    "White wine glass",
    "Nick and Nora Glass",
    "Hurricane glass",
    "Coffee mug",
    "Shot glass",
    "Jar",
    "Irish coffee cup",
    "Punch bowl",
    "Pitcher",
    "Pint glass",
    "Cordial glass",
    "Beer mug",
    "Margarita/Coupette glass",
    "Beer pilsner",
    "Beer Glass",
    "Parfait glass",
    "Wine Glass",
    "Mason jar",
    "Margarita glass",
    "Martini Glass",
    "Balloon Glass",
    "Coupe Glass",
  ],
  categories: [
    "Cocktail",
    "Ordinary Drink",
    "Punch / Party Drink",
    "Shake",
    "Other / Unknown",
    "Cocoa",
    "Shot",
    "Coffee / Tea",
    "Homemade Liqueur",
    "Beer",
    "Soft Drink",
  ],
  ingredients: [
    "Light rum",
    "Bourbon",
    "Vodka",
    "Gin",
    "Blended whiskey",
    "Tequila",
    "Sweet Vermouth",
    "Apricot brandy",
    "Triple sec",
    "Southern Comfort",
    "Orange bitters",
    "Brandy",
    "Lemon vodka",
    "Dry Vermouth",
    "Dark rum",
    "Amaretto",
    "Tea",
    "Applejack",
    "Champagne",
    "Scotch",
    "Coffee liqueur",
    "Añejo rum",
    "Bitters",
    "Sugar",
    "Kahlua",
    "Dubonnet Rouge",
    "Lime juice",
    "Irish whiskey",
    "Apple brandy",
    "Carbonated water",
    "Cherry brandy",
    "Creme de Cacao",
    "Grenadine",
    "Port",
    "Coffee brandy",
    "Red wine",
    "Rum",
    "Grapefruit juice",
    "Ricard",
    "Sherry",
    "Cognac",
    "Sloe gin",
    "Strawberry schnapps",
    "Apple juice",
    "Pineapple juice",
    "Lemon juice",
    "Sugar syrup",
    "Milk",
    "Strawberries",
    "Chocolate syrup",
    "Yoghurt",
    "Mango",
    "Ginger",
    "Lime",
    "Cantaloupe",
    "Berries",
    "Grapes",
    "Kiwi",
    "Tomato juice",
    "Cocoa powder",
    "Chocolate",
    "Heavy cream",
    "Galliano",
    "Peach Vodka",
    "Ouzo",
    "Coffee",
    "Spiced rum",
    "Water",
    "Espresso",
    "Angelica root",
    "Orange",
    "Cranberries",
    "Johnnie Walker",
    "Apple cider",
    "Everclear",
    "Cranberry juice",
    "Egg yolk",
    "Egg",
    "Grape juice",
    "Peach nectar",
    "Lemon",
    "Firewater",
    "Lemonade",
    "Lager",
    "Whiskey",
    "Absolut Citron",
    "Pisco",
    "Irish cream",
    "Ale",
    "Chocolate liqueur",
    "Midori melon liqueur",
    "Sambuca",
    "Cider",
    "Sprite",
    "7-Up",
    "Blackberry brandy",
    "Peppermint schnapps",
    "Creme de Cassis",
    "Jack Daniels",
    "Baileys irish cream",
  ],
  alcohol: ["Alcoholic", "Non alcoholic", "Optional alcohol"],
};
